### ISSUE TITLE
Email/password is wrong.

### ISSUE THREAD

**Issue by apercrcl01** [mjmeli/ha-duke-energy-gateway#100]
At about 2:30PM on Sunday May 22nd my integration stopped working.  I have since tried to restart home assistant multiple times with no luck.  I have now deleted the integration and am trying to readd it.  However, when I enter my email address and password during the configuration I get "Email/password is wrong."  I had just logged into the Duke website with that username/password so I know it is good.  I went ahead and reset my duke password and tried with the new password combination.  I still get "Email/password is wrong".  Below is the error log from before I removed the integration.  Any assistance would be greatly appreciated.  Thank you.

This error originated from a custom integration.

Logger: homeassistant.config_entries
Source: custom_components/duke_energy_gateway/__init__.py:54
Integration: Duke Energy Gateway (documentation, issues)
First occurred: 7:17:01 AM (1 occurrences)
Last logged: 7:17:01 AM

Error setting up entry (redacted) for duke_energy_gateway
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/pyduke_energy/client.py", line 425, in _async_request
    resp.raise_for_status()
  File "/usr/local/lib/python3.9/site-packages/aiohttp/client_reqrep.py", line 1004, in raise_for_status
    raise ClientResponseError(
aiohttp.client_exceptions.ClientResponseError: 500, message='Internal Server Error', url=URL('https://cust-api.duke-energy.com/gep/v2/auth/oauth2/token')

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 335, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/duke_energy_gateway/__init__.py", line 54, in async_setup_entry
    selected_meter, selected_gateway = await client.select_default_meter()
  File "/usr/local/lib/python3.9/site-packages/pyduke_energy/client.py", line 159, in select_default_meter
    account_list = await self.get_account_list()
  File "/usr/local/lib/python3.9/site-packages/pyduke_energy/client.py", line 99, in get_account_list
    headers = await self._get_oauth_headers()
  File "/usr/local/lib/python3.9/site-packages/pyduke_energy/client.py", line 343, in _get_oauth_headers
    await self._oauth_login()
  File "/usr/local/lib/python3.9/site-packages/pyduke_energy/client.py", line 327, in _oauth_login
    resp = await self._async_request(
  File "/usr/local/lib/python3.9/site-packages/pyduke_energy/client.py", line 435, in _async_request
    raise RequestError(
pyduke_energy.errors.RequestError: Request failed with unexpected error [https://cust-api.duke-energy.com/gep/v2/auth/oauth2/token]: (ClientResponseError) 500, message='Internal Server Error', url=URL('https://cust-api.duke-energy.com/gep/v2/auth/oauth2/token')

**Comment by mjmeli** [comment]
I just pushed version 1.0.1 of the HACS integration and it has fixed the issue for me. You can update it via the HACS UI. 

If it doesn't show an update, you can force a check using this button
![image](https://user-images.githubusercontent.com/6422129/170063265-ffb6dd47-1d11-46af-9376-90a6b24afb28.png)
