### ISSUE TITLE
No Gateway Detected - Account Gateway  Access Failure

### ISSUE THREAD

**Issue by agrocker19909** [mjmeli/ha-duke-energy-gateway#112]
Upon initial setup of integration, I get this error message which is self explanatory. What is not obvious, is why my smart meter is not being detected. 

_This error originated from a custom integration.

Logger: homeassistant.config_entries
Source: custom_components/duke_energy_gateway/__init__.py:54
Integration: Duke Energy Gateway (documentation, issues)
First occurred: 12:42:59 PM (1 occurrences)
Last logged: 12:42:59 PM

Error setting up entry **********@gmail.com for duke_energy_gateway
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 339, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/duke_energy_gateway/__init__.py", line 54, in async_setup_entry_
    selected_meter, selected_gateway = await client.select_default_meter()
  File "/usr/local/lib/python3.9/site-packages/pyduke_energy/client.py", line 175, in select_default_meter
    raise DukeEnergyError(
pyduke_energy.errors.DukeEnergyError: Failed to identify any smart meter with gateway access on your account

This is my first time attempting setup, I can confirm I do have the latest Smart Meter from Duke (I called in to confirm) as well as verified the 'OpenWay' meter outside my house. I can login and see a meter ID on my online account that matches my physical smart-meter. I do see energy usage on my account, so I know there is a functional digital meter sending data to my online account.

**Comment by mjmeli** [comment]
This integration requires a gateway device, which is separate from your smart meter. This was previously only available by a pilot program, but the latest I have heard is that they have discontinued distribution of it. There's currently no other way to pull real time usage from Duke's smart meters.

**Comment by agrocker19909** [comment]
Thank you for the response.
