### ISSUE TITLE
Errors when updating config value more than once

### ISSUE THREAD

**Issue by mjmeli** [mjmeli/ha-duke-energy-gateway#48]
Updating the config value for throttling interval works the first time. However, the second time, these errors show up

```
2021-12-03 16:27:35 ERROR (MainThread) [homeassistant.config_entries] Error unloading entry mjmeli94@gmail.com for sensor
Traceback (most recent call last):
  File "/usr/local/python/lib/python3.9/site-packages/homeassistant/config_entries.py", line 452, in async_unload
    result = await component.async_unload_entry(hass, self)  # type: ignore
  File "/usr/local/python/lib/python3.9/site-packages/homeassistant/components/sensor/__init__.py", line 210, in async_unload_entry
    return await component.async_unload_entry(entry)
  File "/usr/local/python/lib/python3.9/site-packages/homeassistant/helpers/entity_component.py", line 177, in async_unload_entry
    raise ValueError("Config entry was never loaded!")
ValueError: Config entry was never loaded!
```

and
```
2021-12-03 16:27:41 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry mjmeli94@gmail.com for sensor
Traceback (most recent call last):
  File "/usr/local/python/lib/python3.9/site-packages/homeassistant/config_entries.py", line 313, in async_setup
    result = await component.async_setup_entry(hass, self)  # type: ignore
  File "/usr/local/python/lib/python3.9/site-packages/homeassistant/components/sensor/__init__.py", line 204, in async_setup_entry
    return await component.async_setup_entry(entry)
  File "/usr/local/python/lib/python3.9/site-packages/homeassistant/helpers/entity_component.py", line 162, in async_setup_entry
    raise ValueError("Config entry has already been setup!")
ValueError: Config entry has already been setup!
```

Everything seems to work fine though

**Comment by mjmeli** [comment]
I've tracked this down to an issue within the integration blueprint. I've raised an issue on that repo.
